name: tempo_clima
description: Sobre o clima

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: 3.0.4
  http: ^0.13.3
  intl: ^0.17.0
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path:

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true